badge: false
crate: openapi_server
creation_timestamp: 1697806193.3045337
distro: mingw64_nt-10.0-20348
duration: 91.25
gnat: 13.1.0
last_attempt: 2025-01-16 01:07:19.912642+00:00
log:
- 'Test ran at 2025-01-16 01:07:19.912642+00:00


  '
- 'SOLUTION:

  '
- "openapi_server=0.7.0: OpenAPI library to build REST server applications\r\n"
- "Origin: commit 91e8ce6ebd894e90fa4876c8ab93a60263108083 from https://gitlab.com/stcarrez/openapi-ada.git\r\
  \n"
- "Properties:\r\n"
- "   Author: Stephane.Carrez@gmail.com\r\n"
- "   Configuration: no modifiers\r\n"
- "   Description: OpenAPI library to build REST server applications\r\n"
- "   Environment: PATH=${CRATE_ROOT}/scripts:${PATH}\r\n"
- "   GPR Scenario: OPENAPI_BUILD := distrib | debug | optimize | profile | coverage\r\
  \n"
- "   GPR Scenario: OPENAPI_LIBRARY_TYPE := relocatable | static | static-pic\r\n"
- "   License: Apache-2.0\r\n"
- "   Long_Description: [![Build Status](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/openapi-ada/badges/build.json)](https://porion.vacs.fr/porion/projects/view/openapi-ada/summary)\r\
  \n"
- "[![Test Status](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/openapi-ada/badges/tests.json)](https://porion.vacs.fr/porion/projects/view/openapi-ada/xunits)\r\
  \n"
- "[![Coverage](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/openapi-ada/badges/coverage.json)](https://porion.vacs.fr/porion/projects/view/openapi-ada/summary)\r\
  \n"
- "\r\n"
- "[OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) is a code\
  \ generator that supports generation of\r\n"
- "API client libraries, server stubs and documentation automatically\r\n"
- "given an [OpenAPI Spec](https://github.com/OAI/OpenAPI-Specification).\r\n"
- "\r\n"
- "The Ada server support has been integrated in [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator).\r\
  \n"
- "\r\n"
- "The OpenAPI Ada library is a small support library for the Ada code generator\r\
  \n"
- "provided by OpenAPI Generator.  The library provides support to serialize the data,\r\
  \n"
- "make HTTP requests and support the [OpenAPI Spec](https://github.com/OAI/OpenAPI-Specification).\r\
  \n"
- "specific operations or types.\r\n"
- "\r\n"
- "## Alire setup\r\n"
- "\r\n"
- "```\r\n"
- "alr with openapi_server\r\n"
- "```\r\n"
- "\r\n"
- "For the server part, you must choose a servlet web container that will handle the\
  \ requests.\r\n"
- "Two web server implementations are provided:\r\n"
- "\r\n"
- "* [AWS](https://github.com/AdaCore/aws)\r\n"
- "* [EWS](https://github.com/simonjwright/ews)\r\n"
- "\r\n"
- "and you should run one of the following `alr` command depending on your choice:\r\
  \n"
- "\r\n"
- "```\r\n"
- "alr with servletada_aws\r\n"
- "alr with servletada_ews\r\n"
- "```\r\n"
- "\r\n"
- "## Generation\r\n"
- "\r\n"
- "Example of server generation with OpenAPI file `my-api.yaml` and use of CURL support:\r\
  \n"
- "\r\n"
- "```\r\n"
- "  alr exec -- openapi-generate-server -i my-api.yaml --additional-properties projectName=MyProject\
  \ --additional-properties openApiName=OpenAPI --additional-properties httpSupport=Curl\
  \ --model-package MyProject.MyModule -o .\r\n"
- "```\r\n"
- "\r\n"
- "\r\n"
- "   Maintainer: Stephane.Carrez@gmail.com\r\n"
- "   Maintainers_Logins: stcarrez\r\n"
- "   Name: openapi_server\r\n"
- "   Project_File: openapi_server.gpr\r\n"
- "   Tag: rest\r\n"
- "   Tag: web\r\n"
- "   Tag: api\r\n"
- "   Tag: openapi\r\n"
- "   Version: 0.7.0\r\n"
- "   Website: https://gitlab.com/stcarrez/openapi-ada\r\n"
- "Dependencies (direct):\r\n"
- "   openapi0.7.0\r\n"
- "   security^1.5.0\r\n"
- "   servletada^1.7.0\r\n"
- "   utilada^2.6.0\r\n"
- "   utilada_xml^2.6.0\r\n"
- "Dependencies (solution):\r\n"
- "   elada=1.8.6\r\n"
- "   gnat=13.1.0 (gnat_native) (installed)\r\n"
- "   openapi=0.7.0\r\n"
- "   security=1.5.0\r\n"
- "   servletada=1.7.0\r\n"
- "   utilada=2.6.0\r\n"
- "   utilada_xml=2.6.0\r\n"
- "   xmlada=23.0.0\r\n"
- "Dependencies (graph):\r\n"
- "   elada=1.8.6          --> utilada=2.6.0 (^2.5.0)          \r\n"
- "   openapi=0.7.0        --> security=1.5.0 (^1.5.0)         \r\n"
- "   openapi=0.7.0        --> utilada=2.6.0 (^2.6.0)          \r\n"
- "   openapi=0.7.0        --> utilada_xml=2.6.0 (^2.6.0)      \r\n"
- "   openapi_server=0.7.0 --> openapi=0.7.0 (0.7.0)           \r\n"
- "   openapi_server=0.7.0 --> security=1.5.0 (^1.5.0)         \r\n"
- "   openapi_server=0.7.0 --> servletada=1.7.0 (^1.7.0)       \r\n"
- "   openapi_server=0.7.0 --> utilada=2.6.0 (^2.6.0)          \r\n"
- "   openapi_server=0.7.0 --> utilada_xml=2.6.0 (^2.6.0)      \r\n"
- "   security=1.5.0       --> utilada=2.6.0 (^2.6.0)          \r\n"
- "   security=1.5.0       --> utilada_xml=2.6.0 (^2.6.0)      \r\n"
- "   servletada=1.7.0     --> elada=1.8.6 (^1.8.5)            \r\n"
- "   servletada=1.7.0     --> security=1.5.0 (^1.5.0)         \r\n"
- "   servletada=1.7.0     --> utilada=2.6.0 (^2.6.0)          \r\n"
- "   utilada_xml=2.6.0    --> utilada=2.6.0 (^2.6.0)          \r\n"
- "   utilada_xml=2.6.0    --> xmlada=23.0.0 (*)               \r\n"
- "   xmlada=23.0.0        --> gnat=13.1.0 (gnat_native) (>=11)\r\n"
- '

  '
- '

  LOG:

  '
- 'Failed to locate log

  '
platform: windows
status: success
version: 0.7.0
