badge: false
crate: openapi
creation_timestamp: 1738758652.956217
distro: mingw64_nt-10.0-20348
duration: 0.0
gnat: 14.2.1
last_attempt: never
log:
- no log available
platform: windows
status: untested
version: 0.8.0
