badge: false
crate: openapi_server
creation_timestamp: 1738715876.654123
distro: darwin-23.6.0
duration: 0.0
gnat: 14.2.1
last_attempt: never
log:
- no log available
platform: macos
status: untested
version: 0.8.0
