name: CI linux

on:
  pull_request:

env:
  alire_index: ""
  # Empty index: test with master of community index
  # Otherwise: test with particular commit/branch
  # e.g.: index: "git+https://github.com/alire-project/alire-index@deadbeef"

jobs:

  build:
    name: CI on ${{ matrix.tag }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: # Those are our dockerhub alire/gnat:tag machines
            - centos-latest-community-2019
            - community-current
            - debian-stable
            - ubuntu-lts

    steps:
    - name: Check out repository
      uses: actions/checkout@v1

    - name: Check out submodules
      run: git submodule update --init --recursive

    - name: Pull docker image
      run: docker pull alire/gnat:${{ matrix.tag }}

    - name: Run test script
      run: >
        docker run -v${PWD}:/alire -w /alire 
        -e "SETUP_NAME=${{ matrix.tag}}"
        -e "INDEX=${{ env.alire_index }}"
        -e "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
        -e GITHUB_ACTOR
        -e GITHUB_REPOSITORY
        -e GITHUB_SHA
        alire/gnat:${{ matrix.tag }} ./test-script.sh
