badge: true
badge_color: inactive
crate: openapi_server
creation_timestamp: 1696987028.114659
distro: debian-12
duration: 0.993244523000044
gnat: 12.2.0
last_attempt: 2024-03-08 01:11:27.712739+00:00
log:
- 'Test ran at 2024-03-08 01:11:27.712671+00:00


  '
- 'SOLUTION:

  '
- 'Not found: openapi_server=0.7.0

  '
- '

  '
- '

  LOG:

  '
- 'Failed to locate log

  '
platform: linux
status: internal-ci-error
version: 0.7.0
