badge: false
crate: openapi_server
creation_timestamp: 1738707502.7551894
distro: ubuntu-24.04
duration: 0.0
gnat: 14.2.1
last_attempt: never
log:
- no log available
platform: linux
status: untested
version: 0.8.0
