badge: false
crate: flux
creation_timestamp: 1739363227.3878913
distro: mingw64_nt-10.0-20348
duration: 3.6410000000000764
gnat: 10.3.2
last_attempt: 2025-07-24 12:48:27.734751+00:00
log:
- 'Test ran at 2025-07-24 12:48:27.734751+00:00


  '
- 'SOLUTION:

  '
- 'flux=1.0.0: Experimental data stream library for Ada

  '
- 'Origin: commit 688d2c90e075aff1d225958682141d6476f03ea7 from https://github.com/Fabien-Chouteau/flux.git

  '
- 'Properties:

  '
- '   Author: Fabien Chouteau

  '
- '   Config type: Enable_File_IO : Boolean default: ''true''

  '
- '   Configuration: no modifiers

  '
- '   Description: Experimental data stream library for Ada

  '
- '   License: Apache-2.0

  '
- '   Maintainer: Fabien Chouteau <chouteau@adacore.com>

  '
- '   Maintainers_Logins: Fabien-Chouteau

  '
- '   Name: flux

  '
- '   Version: 1.0.0

  '
- '

  '
- '

  LOG:

  '
- '[alr test] Testing flux=1.0.0

  '
- '[alr test] Spawning retrieval for remote crate: alr -d -n get flux=1.0.0

  '
- 'Note: Deploying flux=1.0.0...

  '
- '

  '
- 'flux=1.0.0 successfully retrieved.

  '
- 'There are no dependencies.

  '
- '[alr test] Spawning default test for remote crate: alr -d -n build --release --
  -cargs:Ada -gnatwn

  '
- 'Note: Building flux=1.0.0/flux.gpr...

  '
- 'Setup

  '
- '   [mkdir]        object directory for project Flux

  '
- '   [mkdir]        library directory for project Flux

  '
- 'Compile

  '
- '   [Ada]          flux-traits-file_io.ads

  '
- '   [Ada]          flux-traits-file_io-sink.adb

  '
- '   [Ada]          flux-interfaces-file_io.ads

  '
- '   [Ada]          flux-interfaces-file_io-source.adb

  '
- '   [Ada]          flux-interfaces-file_io-sink.adb

  '
- '   [Ada]          flux_config.ads

  '
- '   [Ada]          flux.ads

  '
- '   [Ada]          flux-traits.ads

  '
- '   [Ada]          flux-traits-source.ads

  '
- '   [Ada]          flux-traits-sink.ads

  '
- '   [Ada]          flux-traits-seekable_source.ads

  '
- '   [Ada]          flux-traits-memory_source.adb

  '
- '   [Ada]          flux-traits-memory_sink.adb

  '
- '   [Ada]          flux-traits-memory_duplex.adb

  '
- '   [Ada]          flux-traits-leb128.adb

  '
- '   [Ada]          flux-traits-hexdump.adb

  '
- '   [Ada]          flux-traits-duplex.ads

  '
- '   [Ada]          flux-traits-bounded_array_source.adb

  '
- 'flux-traits-bounded_array_source.ads:45:04: instantiation error at flux-traits-seekable_source.ads:38

  '
- 'flux-traits-bounded_array_source.ads:45:04: no visible subprogram matches the specification
  for "Read"

  '
- '

  '
- '   compilation of flux-traits-bounded_array_source.adb failed

  '
- '

  '
- 'gprbuild: *** compilation phase failed

  '
- 'stderr: Command ["gprbuild", "-s", "-j0", "-p", "-P", "D:\a\alire-crates-ci\alire-crates-ci\test\66d3786c-ae7d-498f-a7f3-f4ac515fecbe\flux_1.0.0_688d2c90\flux.gpr",
  "-cargs:Ada", "-gnatwn"] exited with code 4

  '
- 'ERROR: Command ["gprbuild", "-s", "-j0", "-p", "-P", "D:\a\alire-crates-ci\alire-crates-ci\test\66d3786c-ae7d-498f-a7f3-f4ac515fecbe\flux_1.0.0_688d2c90\flux.gpr",
  "-cargs:Ada", "-gnatwn"] exited with code 4

  '
- 'stderr: ALIRE.CHECKED_ERROR

  '
- 'stderr: Command ["gprbuild", "-s", "-j0", "-p", "-P", "D:\a\alire-crates-ci\alire-crates-ci\test\66d3786c-ae7d-498f-a7f3-f4ac515fecbe\flux_1.0.0_688d2c90\flux.gpr",
  "-cargs:Ada", "-gnatwn"] exited with code 4

  '
- 'stderr: raised ALIRE.CHECKED_ERROR : alire-stored-error:1

  '
- '[D:\a\alire-crates-ci\alire-crates-ci\alire_install\bin\alr.exe]

  '
- '0x7ff7f37bda2a Semantic_Versioning.Basic.Restrictions.First_Index at alire.adb:284

  '
- '0x7ff7f33b595b Semantic_Versioning.Basic.Restrictions.First_Index at alire-os_lib-subprocess.adb:111

  '
- '0x7ff7f366cba1 Semantic_Versioning.Basic.Restrictions.First_Index at alire-spawn.adb:22

  '
- '0x7ff7f366dd5d Semantic_Versioning.Basic.Restrictions.First_Index at alire-spawn.adb:68

  '
- '0x7ff7f3592d64 Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:189

  '
- '0x7ff7f35911da Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:255

  '
- '0x7ff7f35b912d Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:2143

  '
- '0x7ff7f36282f9 Semantic_Versioning.Basic.Restrictions.First_Index at alire-solutions.adb:1472

  '
- '0x7ff7f3627424 Semantic_Versioning.Basic.Restrictions.First_Index at alire-solutions.adb:1555

  '
- '0x7ff7f35b922c Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:2147

  '
- '0x7ff7f35b92fa Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:2127

  '
- '0x7ff7f35917a7 Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:286

  '
- '0x7ff7f3591912 Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:114

  '
- '0x7ff7f2d03baa Semantic_Versioning.Basic.Restrictions.First_Index at alr-commands-build.adb:145

  '
- '0x7ff7f2d0341e Semantic_Versioning.Basic.Restrictions.First_Index at alr-commands-build.adb:113

  '
- '0x7ff7f2d035ba Semantic_Versioning.Basic.Restrictions.First_Index at alr-commands-build.adb:54

  '
- '0x7ff7f2db5dea Semantic_Versioning.Basic.Restrictions.First_Index at clic-subcommand-instance.adb:749

  '
- '0x7ff7f2dc2b0e Semantic_Versioning.Basic.Restrictions.First_Index at alr-commands.adb:632

  '
- '0x7ff7f2c916a0 Alr.Main at alr-main.adb:13

  '
- '0x7ff7f2c95270 Main at b__alr-main.adb:2454

  '
- '0x7ff7f2c9133e __tmainCRTStartup at ???

  '
- '0x7ff7f2c91144 mainCRTStartup at ???

  '
- '[C:\Windows\System32\KERNEL32.DLL]

  '
- '0x7ffc62cd4cae

  '
- '[C:\Windows\SYSTEM32\ntdll.dll]

  '
- '0x7ffc63d5edc9

  '
- '

  '
- 'stderr: ALIRE.ROOTS.BUILD._WRAPPED_STATEMENTS.BUILD_FAILED

  '
- 'stderr: alire-roots.adb:202

  '
- 'stderr: raised ALIRE.ROOTS.BUILD._WRAPPED_STATEMENTS.BUILD_FAILED : alire-roots.adb:202

  '
- '[D:\a\alire-crates-ci\alire-crates-ci\alire_install\bin\alr.exe]

  '
- '0x7ff7f359313c Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:202

  '
- '0x7ff7f35911da Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:255

  '
- '0x7ff7f35b912d Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:2143

  '
- '0x7ff7f36282f9 Semantic_Versioning.Basic.Restrictions.First_Index at alire-solutions.adb:1472

  '
- '0x7ff7f3627424 Semantic_Versioning.Basic.Restrictions.First_Index at alire-solutions.adb:1555

  '
- '0x7ff7f35b922c Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:2147

  '
- '0x7ff7f35b92fa Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:2127

  '
- '0x7ff7f35917a7 Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:286

  '
- '0x7ff7f3591912 Semantic_Versioning.Basic.Restrictions.First_Index at alire-roots.adb:114

  '
- '0x7ff7f2d03baa Semantic_Versioning.Basic.Restrictions.First_Index at alr-commands-build.adb:145

  '
- '0x7ff7f2d0341e Semantic_Versioning.Basic.Restrictions.First_Index at alr-commands-build.adb:113

  '
- '0x7ff7f2d035ba Semantic_Versioning.Basic.Restrictions.First_Index at alr-commands-build.adb:54

  '
- '0x7ff7f2db5dea Semantic_Versioning.Basic.Restrictions.First_Index at clic-subcommand-instance.adb:749

  '
- '0x7ff7f2dc2b0e Semantic_Versioning.Basic.Restrictions.First_Index at alr-commands.adb:632

  '
- '0x7ff7f2c916a0 Alr.Main at alr-main.adb:13

  '
- '0x7ff7f2c95270 Main at b__alr-main.adb:2454

  '
- '0x7ff7f2c9133e __tmainCRTStartup at ???

  '
- '0x7ff7f2c91144 mainCRTStartup at ???

  '
- '[C:\Windows\System32\KERNEL32.DLL]

  '
- '0x7ffc62cd4cae

  '
- '[C:\Windows\SYSTEM32\ntdll.dll]

  '
- '0x7ffc63d5edc9

  '
- '

  '
- 'ERROR: Compilation failed.

  '
platform: windows
status: failing
version: 1.0.0
