badge: false
crate: openapi
creation_timestamp: 1738707504.57629
distro: ubuntu-24.04
duration: 0.0
gnat: 13.2.2
last_attempt: never
log:
- no log available
platform: linux
status: untested
version: 0.8.0
