badge: true
badge_color: green
crate: flux
creation_timestamp: 1750683801.6077812
distro: arch-20250601.0.358000
duration: 1.8227022319999833
gnat: 15.1.1
last_attempt: 2025-06-26 01:24:41.846124+00:00
log:
- 'Test ran at 2025-06-26 01:24:41.846101+00:00


  '
- 'SOLUTION:

  '
- 'flux=1.0.0: Experimental data stream library for Ada

  '
- 'Origin: commit 688d2c90e075aff1d225958682141d6476f03ea7 from https://github.com/Fabien-Chouteau/flux.git

  '
- 'Properties:

  '
- '   Author: Fabien Chouteau

  '
- '   Config type: Enable_File_IO : Boolean default: ''true''

  '
- '   Configuration: no modifiers

  '
- '   Description: Experimental data stream library for Ada

  '
- '   License: Apache-2.0

  '
- '   Maintainer: Fabien Chouteau <chouteau@adacore.com>

  '
- '   Maintainers_Logins: Fabien-Chouteau

  '
- '   Name: flux

  '
- '   Version: 1.0.0

  '
- '

  '
- '

  LOG:

  '
- 'Spawning: alr -d -n get --build flux=1.0.0

  '
- 'Note: Deploying flux=1.0.0...

  '
- 'Note: Building flux=1.0.0/flux.gpr...

  '
- 'Setup

  '
- '   [mkdir]        object directory for project Flux

  '
- '   [mkdir]        library directory for project Flux

  '
- 'Compile

  '
- '   [Ada]          flux-interfaces-file_io.ads

  '
- '   [Ada]          flux-interfaces-file_io-sink.adb

  '
- '   [Ada]          flux-interfaces-file_io-source.adb

  '
- '   [Ada]          flux-traits-file_io-sink.adb

  '
- '   [Ada]          flux-traits-file_io.ads

  '
- '   [Ada]          flux_config.ads

  '
- '   [Ada]          flux-traits-bounded_array_source.adb

  '
- '   [Ada]          flux-interfaces-bounded_array-source-as_traits.ads

  '
- '   [Ada]          flux-interfaces-hexdump.adb

  '
- '   [Ada]          flux-interfaces-bounded_array-sink-as_traits.ads

  '
- '   [Ada]          flux-interfaces-leb128.adb

  '
- '   [Ada]          flux-interfaces-bounded_array-sink.adb

  '
- '   [Ada]          flux-traits-bounded_array_duplex.adb

  '
- '   [Ada]          flux-interfaces-as_traits-sink.adb

  '
- '   [Ada]          flux-interfaces-bounded_array-source.adb

  '
- '   [Ada]          flux-traits-hexdump.adb

  '
- '   [Ada]          flux-interfaces-source.ads

  '
- '   [Ada]          flux-traits-sink.ads

  '
- '   [Ada]          flux-interfaces-sink.ads

  '
- '   [Ada]          flux-interfaces-seekable_source.ads

  '
- '   [Ada]          flux-interfaces.ads

  '
- '   [Ada]          flux-traits-memory_sink.adb

  '
- '   [Ada]          flux-interfaces-as_traits-duplex.adb

  '
- '   [Ada]          flux.ads

  '
- '   [Ada]          flux-traits-seekable_source.ads

  '
- '   [Ada]          flux-interfaces-bounded_array-duplex-as_traits.ads

  '
- '   [Ada]          flux-traits-duplex.ads

  '
- '   [Ada]          flux-traits-leb128.adb

  '
- '   [Ada]          flux-interfaces-bounded_array-duplex.adb

  '
- '   [Ada]          flux-traits.ads

  '
- '   [Ada]          flux-slice.adb

  '
- '   [Ada]          flux-traits-source.ads

  '
- '   [Ada]          flux-traits-memory_duplex.adb

  '
- '   [Ada]          flux-traits-bounded_array_sink.adb

  '
- '   [Ada]          flux-interfaces-bounded_array.ads

  '
- '   [Ada]          flux-traits-memory_source.adb

  '
- '   [Ada]          flux-interfaces-as_traits.ads

  '
- '   [Ada]          flux-interfaces-as_traits-source.adb

  '
- 'Build Libraries

  '
- '   [gprlib]       Flux.lexch

  '
- '   [archive]      libFlux.a

  '
- '   [index]        libFlux.a

  '
- '

  '
- 'flux=1.0.0 successfully retrieved and built.

  '
- 'There are no dependencies.

  '
- 'Found declared GPR file: flux.gpr

  '
platform: linux
status: success
version: 1.0.0
