badge: false
crate: openapi
creation_timestamp: 1711067714.8856099
distro: darwin-21.6.0
duration: 8.784108832999891
gnat: 12.2.1
last_attempt: 2025-01-18 00:38:21.971950+00:00
log:
- 'Test ran at 2025-01-18 00:38:21.971844+00:00


  '
- 'SOLUTION:

  '
- 'Not found: openapi=0.7.0

  '
- '

  '
- '

  LOG:

  '
- 'Failed to locate log

  '
platform: macos
status: internal-ci-error
version: 0.7.0
