name: CI with Alire compilers

on:
  schedule:
    - cron: '13 */12 * * *'
#  push:
#    branches: ["master", "devel"]

jobs:

  exp:

    name: Test on ${{ matrix.os }} with gnat${{ matrix.gnat_version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        gnat_version:
          - ^10
          - ^11

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up stable `alr`
      uses: alire-project/setup-alire@v1
      with:
        toolchain: gnat${{ matrix.gnat_version }} gprbuild

    - name: Decide badging
      id : set-badge
      if: ${{ matrix.gnat_version }} == '^11'
      run: echo '::set-output BADGE=1'

    - name: Test release
      run: scripts/run-tests.sh
      shell: bash
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        DISTRO: ${{ matrix.os }}
        BADGE: ${{ steps.set-badge.outputs.BADGE }}