name: CI with Alire compilers

on:
  pull_request:
  schedule:
    - cron: '13 */12 * * *'
  #  push:
  #    branches: ["master", "devel"]
  workflow_dispatch: # Allow manual triggering

jobs:

  exp:

    name: ${{ matrix.os }}::gnat${{ matrix.gnat_version }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        gnat_version:
          - ^10
          - ^11
          - ^12
          - ^13
          - "" # Ensure latest is tested even if we forget to update the matrix
        exclude: # We don't have full toolchain for those (yet?)
          - os: macos-latest
            gnat_version: ^10
          - os: macos-latest
            gnat_version: ^11
          - os: macos-latest
            gnat_version: ^12

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up stable `alr`
      uses: alire-project/setup-alire@v4
      with:
        toolchain: gnat_native${{ matrix.gnat_version }} gprbuild

    - name: Decide badging
      id : set-badge
      if: ${{ matrix.gnat_version }} == ''
      run: echo '::set-output BADGE=1'

    # For runs triggered by a pull request, we'll do only one crate test
    - name: Decide short run
      id : short-run
      if: ${{ github.event_name == 'pull_request' }}
      run: echo 'output=true' >> $GITHUB_OUTPUT
      shell: bash

    - name: Test release
      run: scripts/run-tests.sh
      shell: bash
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        DISTRO:      ${{ matrix.os }}
        BADGE:       ${{ steps.set-badge.outputs.BADGE }}
        SHORT_RUN:   ${{ steps.short-run.outputs.output }}