name: Update gh-pages branch and trigger jekyll
on:
  schedule:
    - cron:  '55 * * * *'
#  push:
#    branches: [ "master", "website" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Set up Python dependencies
        run: pip3 install -r requirements.txt

      - run: bash -v prepare-site.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_UPDATE }}

      - name: Request Github Pages build job
        run: >-
          curl -L -X POST
          -H "Content-Type: application/json"
          -H "Authorization: token ${{ secrets.GH_PAGES_UPDATE }}"
          "https://api.github.com/repos/${{ github.repository }}/pages/builds"
